import { z } from 'zod';

// Zod schemas mirror the TypeScript interfaces in src/types/workspace.ts.
// They validate any data crossing a trust boundary: file -> store,
// renderer -> main IPC, and (later) imported YAML/JSON.

export const commandModeSchema = z.enum(['terminal', 'output']);

export const workspaceCommandSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  command: z.string().min(1),
  mode: commandModeSchema,
  dangerous: z.boolean().optional(),
  confirm: z.boolean().optional(),
  isLog: z.boolean().optional()
});

export const serviceCheckSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  command: z.string().min(1),
  expected: z.string().min(1)
});

export const workspaceSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  hostLabel: z.string().optional(),
  hostname: z.string().min(1),
  port: z.number().int().min(1).max(65535).default(22),
  username: z.string().min(1),
  identityFile: z.string().optional(),
  remotePath: z.string().optional(),
  env: z.record(z.string()).optional(),
  commands: z.array(workspaceCommandSchema).default([]),
  serviceChecks: z.array(serviceCheckSchema).default([])
});

export const workspacesFileSchema = z.object({
  version: z.literal(1),
  workspaces: z.array(workspaceSchema)
});

// Input schema used when creating/updating from the renderer form:
// `id` is optional (generated by the store on create).
export const workspaceInputSchema = workspaceSchema.extend({
  id: z.string().optional()
});

export type WorkspaceInput = z.input<typeof workspaceInputSchema>;
